# Generated by Django 4.1.3 on 2022-11-10 09:52

import django.db.models.deletion
import mptt.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50, verbose_name='Страна')),
                ('city', models.CharField(max_length=50, verbose_name='Город')),
                ('street', models.CharField(max_length=50, verbose_name='Улица')),
                ('house', models.CharField(max_length=10, verbose_name='Номер дома')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Электронная почта')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='sale_objects.address', verbose_name='Адресс')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Название')),
                ('model', models.CharField(max_length=25, verbose_name='Модель')),
                ('on_sale_date', models.DateField(verbose_name='Дата выхода продукта на рынок')),
            ],
        ),
        migrations.CreateModel(
            name='SaleObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('factory', 'Завод'), ('distributor', 'Дистрибьютор'), ('dealership', 'Дилерский центр'), ('retail', 'Крупная розничная сеть'), ('individual', 'Индивидуальный предприниматель')], max_length=15)),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('debt', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Задолженность перед поставщиком')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('contacts', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sale_objects.contact', verbose_name='Контакты')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='sale_objects.saleobject', verbose_name='Поставщик')),
                ('products', models.ManyToManyField(to='sale_objects.product', verbose_name='Продукты')),
                ('workers', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Сотрудники')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
